name: test
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 < 4.0.0'

dependencies:

dev_dependencies:
  flutter_lints: ^3.0.1